"""Schematic radar of all areas/links in a generated spatial graph.

Preview footprints are display glyphs, not learned room polygons or VMAP meshes.
"""
import json
import math
from pathlib import Path
import numpy as np
from PIL import Image,ImageDraw,ImageFont,ImageFilter
from train_route_organization import sha


def main():
    root=Path(__file__).resolve().parent;folder=root/'output/training/progressive-layout-v2'
    source=folder/'samples.json';sample=json.loads(source.read_text())[0]
    x=np.asarray(sample['descriptors']);roles=np.asarray(sample['roles']);adj=np.asarray(sample['adjacency']);n=len(x)
    size=1200;factor=2
    extent=np.maximum(np.ptp(x[:,:2],axis=0),.05);scale=min(1000/extent[0],1000/extent[1]);center=(x[:,:2].max(0)+x[:,:2].min(0))/2
    pos=(x[:,:2]-center)*scale;pos[:,0]+=600;pos[:,1]=600-pos[:,1]
    radius=np.clip(np.sqrt(np.expm1(x[:,4])/math.pi)*scale*.22,5,22)
    floor=Image.new('L',(size*factor,size*factor),0);draw=ImageDraw.Draw(floor)
    links=list(zip(*np.nonzero(np.triu((adj+adj.T)>0,1))))
    def xy(i):return tuple(pos[i]*factor)
    for u,v in links:draw.line([xy(u),xy(v)],fill=255,width=6*factor)
    for i in range(n):
        # Octagonal glyph centered exactly at the generated position.
        points=[tuple((pos[i]+radius[i]*np.array([math.cos(k*math.pi/4),math.sin(k*math.pi/4)]))*factor) for k in range(8)]
        draw.polygon(points,fill=255)
    floor=floor.resize((size,size),Image.Resampling.LANCZOS)
    canvas=Image.new('RGB',(1580,1410),'#111a23');pen=ImageDraw.Draw(canvas)
    font=lambda s:ImageFont.truetype('C:/Windows/Fonts/arial.ttf',s)
    pen.text((30,20),'Generated layout — radar preview',font=font(34),fill='#f2f4f6')
    pen.text((30,68),f"Fixed seed {sample['seed']} | {n} generated areas | all connections shown",font=font(21),fill='#b4c1cb')
    radar=Image.new('RGB',(size,size),'#080e14');grid=ImageDraw.Draw(radar)
    for k in range(0,size,100):
        grid.line([(k,0),(k,size)],fill='#15212c');grid.line([(0,k),(size,k)],fill='#15212c')
    outline=floor.filter(ImageFilter.MaxFilter(5));radar.paste('#85919a',(0,0),outline);radar.paste('#526371',(0,0),floor)
    rd=ImageDraw.Draw(radar)
    # Height is not converted into stacked floors; preserve the top-down graph.
    for i in range(n):
        px,py=pos[i];rd.ellipse((px-1,py-1,px+1,py+1),fill='#a1b1bc')
    offsets={'T':(-10,20),'CT':(12,-35),'A':(-18,-37),'B':(12,-29)}
    for bit,name in enumerate(('T','CT','A','B')):
        indices=np.flatnonzero(roles&(1<<bit));color='#f3a43e' if name=='T' else '#5ec9ee' if name=='CT' else '#f3dc74'
        for j,i in enumerate(indices,1):
            px,py=pos[i];r=14 if name in ('T','CT') else 10
            rd.ellipse((px-r,py-r,px+r,py+r),fill=color,outline='#090f15',width=3)
            label=name if len(indices)==1 else f'{name}{j}';dx,dy=offsets[name];tx,ty=px+dx,py+dy
            box=rd.textbbox((tx,ty),label,font=font(21));rd.rounded_rectangle((box[0]-5,box[1]-3,box[2]+5,box[3]+3),radius=4,fill='#080e14')
            rd.text((tx,ty),label,font=font(21),fill=color)
    canvas.paste(radar,(25,115));pen=ImageDraw.Draw(canvas)
    sx=1250;pen.text((sx,150),'LEGEND',font=font(26),fill='white')
    for yy,color,label in [(215,'#f3a43e','T spawn'),(270,'#5ec9ee','CT spawn'),(325,'#f3dc74','A / B regions'),(380,'#526371','Areas and links')]:
        pen.ellipse((sx,yy+2,sx+19,yy+21),fill=color);pen.text((sx+32,yy),label,font=font(21),fill='#d0d9df')
    lines=['This is the model output,','not a finished CS2 map.','','Positions and links are','generated by the model.','','Octagons and narrow bands','are schematic footprints.','Walls and passage widths','have not been learned.','','A1/A2 and B1–B4 are','repeated role-marked areas,','not six intended bombsites.','','Crossings are not verified','junctions or overpasses.','','Isolated regions remain','visible in this preview.']
    for j,line in enumerate(lines):pen.text((sx,460+j*31),line,font=font(18),fill='#b9c6d0')
    pen.text((30,1340),'Schematic preview: native positions and links retained; no connectivity repair or Hammer geometry.',font=font(21),fill='#d9ba78')
    output=folder/'generated-radar.png';canvas.save(output)
    metadata={'sample_seed':sample['seed'],'samples_sha256':sha(source),'nodes_rendered':n,'undirected_link_glyphs':len(links),
              'source_directed_edges':int(adj.sum()),'graph_or_positions_modified':False,'all_nodes_and_links_rendered':True,
              'display_footprints':'octagons with area-scaled radii clipped to 5–22px; straight 6px link bands',
              'semantic_scope':'radar-style spatial graph preview, not generated architecture or verified walkable floorplan','output':str(output.resolve())}
    (folder/'generated-radar.json').write_text(json.dumps(metadata,indent=2),encoding='utf-8')
    print(json.dumps(metadata))


if __name__=='__main__':main()
