"""Post-search visual diversity review; never changes candidate geometry or gates."""
import json
from collections import Counter
from pathlib import Path
from PIL import Image
from procedural_p04 import ROOT
from playable_composition import compile_composition
from p04_comparison_round import render

def main():
    out=ROOT/'output/p04-frozen-search-001';s=json.loads((out/'summary.json').read_text());cfg=json.loads((out/'configuration.json').read_text());passes=s['physical_passes'];selected=[passes[0]] if passes else []
    result=dict(selected_candidates_for_review=selected,physical_structural_survivors=passes,valid_but_not_counted=[x for x in passes if x not in selected],total_attempts=s['total_attempts'],diversity_target_met=False,
        explanation='Visual comparison collapses all nine survivors to one major organization: parallel site chains between a shared front deployment and shared rear deployment. Stagger, dimensions, local gallery reflection and small connector changes do not qualify. The automatic prefilter detected two circulation signatures; its inter-complex threshold was sensitive to depth offsets, so that distinction is not accepted as a second composition.',gate_results_changed=False,candidate_geometry_changed=False)
    (out/'final-diversity-review.json').write_text(json.dumps(result,indent=2))
    clean=Image.new('RGB',(2700,2475),'#101923');overlays=Image.new('RGB',(2700,2475),'#101923')
    for i,seed in enumerate(passes):
        folder=out/f'seed-{seed}';p=json.loads((folder/'composition.json').read_text());v=json.loads((folder/'validation.json').read_text());c=compile_composition(p)
        display=dict(p,display_title=f'Seed {seed} / physical pass / '+('candidate for review' if seed in selected else 'same composition family — retained'))
        for overlay,sheet in [(False,clean),(True,overlays)]:
            im=render(display,c,v,seed,(0,0,*cfg['world']),overlay,s['common_pixels_per_plan_unit']);sheet.paste(im.resize((900,825)),((i%3)*900,(i//3)*825))
            if seed in selected:im.save(out/('candidate-clean.png' if not overlay else 'candidate-encounters.png'))
    clean.save(out/'survivors-clean-common-scale.png');overlays.save(out/'survivors-encounters-common-scale.png')
    families={f:{'attempts':0,'passes':0} for f in ('parallel','inward','outward')};reasons=Counter()
    for a in s['attempts']:
        families[a['family']]['attempts']+=1;families[a['family']]['passes']+=int(a['physical_structural_pass'])
        for category,prefix in [('Short disjoint deployment not found','No short disjoint deployment'),('Connector exceeds 1536 HU cap','Spawn connector exceeds'),('Disjoint connector not found','No disjoint circulation'),('Required route unreachable','Unreachable ordered route'),('Wrong/equivalent entry sector','Equivalent or wrong alternate ingress'),('Rotation bypass/shortcut','Shortest rotation bypasses'),('Aperture interference','Aperture interference'),('Disconnected components','Disconnected walkable')]:
            if any(v.startswith(prefix) for v in a['violations']):reasons[category]+=1
    report=['# Frozen P04 search — final review','', '**40 attempts, 9 physical/structural passes, 1 major composition selected for review. The four-distinct-composition target was not met.**','', 'Seeds 10001–10040 were previously untested. All previous outputs remain intact. Rules, v3 configuration and acceptance checks were frozen before the search and hash-verified afterward. No candidate-specific repairs, rule updates or weakened gates. Stage 4 and engine geometry remain paused.','', '## Separate evaluations','', result['explanation'],'', 'The initial automated classification remains in summary.json, attempts.jsonl and per-seed validations for audit. This final diversity review supersedes its two preliminary selections; physical results are unchanged. No architectural changes occurred during review.','', '## Arrangement-family coverage','', '| Relative B orientation | Attempts | Physical/structural passes |','|---|---:|---:|']
    for f,n in families.items():report.append(f'| {f} | {n["attempts"]} | {n["passes"]} |')
    report+=['', 'Axis coverage (axis changes alone do not qualify): '+json.dumps(s['family_coverage']), '', '## Survivor comparison','', '| Seeds | Spatial differences | Diversity decision |','|---|---|---|', '| 10007 | A and B staggered substantially in depth; CT–A corridor occupies part of the inter-site gap. | Representative candidate for review; not visually accepted. |', '| 10008, 10012 | Opposite staggering and local gallery sides; 10008 changes global axis. | Same front/rear deployment and parallel site-chain organization. |', '| 10013, 10018, 10026, 10030, 10032, 10034 | More aligned sites, different local widths, galleries and connector bends. | Not counted: alignment/spacing/local detail within the same organization. |','', 'All nine retain separate T commitments, B investment, local alternative entries, rear CT circulation and no Mid under the frozen checks. The local architectural vocabulary remains repetitive. Passing candidates have CT same-encounter arrival-distance warnings at both sites; timing is unresolved. No claims of balance, good encounter control or visual acceptance.','', '## Rejection reasons','', 'Counts below are candidates affected; categories overlap. Every exact violation is retained per seed.','']
    report += [f'- {k}: {n}' for k,n in reasons.items()]
    report+=['', 'There were 31 physical/structural rejections. The perpendicular families cannot reliably obtain short, disjoint connections with this frozen packing and bounded deployment/router procedure. A failure is evidence of this procedure’s limitation, not proof the strategy is spatially impossible. Eight valid survivors were excluded from the distinct-selection count.','', '## Artifacts','', '[All physical survivors, identical scale](survivors-clean-common-scale.png) · [Their encounter overlays](survivors-encounters-common-scale.png)','', '[Selected candidate clean plan](candidate-clean.png) · [Selected candidate encounter overlay](candidate-encounters.png)','', 'All proposal geometry, decision logs, validation, images and full reproduction hashes are under seed-N directories. attempts.jsonl contains every attempt. frozen/ preserves rules, checks and dependencies; manifest.json preserves their hashes and all 40 predeclared seeds.','', '## Commands','', 'Original generation command from repository root:','', '```powershell', '.tools\\training\\Scripts\\python.exe search_frozen_p04.py', '```','', 'Reproduce any recorded seed using the frozen snapshot (use a fresh output directory):','', '```powershell', '.tools\\training\\Scripts\\python.exe replay_frozen_p04.py --experiment output/p04-frozen-search-001 --seed 10007 --output output/p04-replay-10007', '```','', 'The search command intentionally disallows reusing tested seeds. Use the replay command for reproduction. All 40 proposals were generated twice with equal complete composition/decision hashes. An independent replay of 10007 from frozen sources also matched. Nine existing generator regression tests passed.','', 'The experiment is finished and stopped for review. No extra seeds or generation-rule changes were performed.']
    (out/'final-review.md').write_text('\n'.join(report),encoding='utf-8')
    old=out/'review.md';old.write_text('**Superseded by [final visual diversity review](final-review.md).** The automated prefilter found two signatures; final review counts one major composition. Use replay_frozen_p04.py for recorded-seed reproduction.\n\n'+old.read_text(),encoding='utf-8')
    policy_path=ROOT/'generation-policy.json';policy=json.loads(policy_path.read_text());policy.update(stage_3_review='output/p04-frozen-search-001/final-review.md',stage_3_experiment_status='frozen_search_complete_diversity_shortfall',stage_3_frozen_search=dict(attempts=40,seed_range=[10001,10040],physical_passes=9,distinct_selections=selected,consumed=True),stage_4_authorized=False,stage_3_batch_authorized=False,geometry_paused=True);policy_path.write_text(json.dumps(policy,indent=2)+'\n')
    print(json.dumps(dict(families=families,rejection_categories=reasons,final_review=result)))

if __name__=='__main__':main()
